
const products = [
  {
    id: 1,
    name: "iPhone 14 Pro",
    description: "Apple smartphone with A16 Bionic chip",
    price: 1299,
    image: "/assets/14pro.jpg",
  },
  {
    id: 2,
    name: "Samsung Galaxy S23",
    description: "Flagship Android phone with Snapdragon 8 Gen 2",
    price: 1199,
    image: "/assets/s23.jpg",
  },
  {
    id: 3,
    name: "MacBook Air M2",
    description: "Lightweight laptop with Apple's M2 chip",
    price: 999,
    image: "/assets/macbookaim2.jpg",
  },
  {
    id: 4,
    name: "Dell XPS 13",
    description: "Premium Windows laptop with sleek design",
    price: 1099,
    image: "/assets/dellxps13.jpg",
  },
  {
    id: 5,
    name: "iPad Pro",
    description: "Powerful tablet with Liquid Retina display",
    price: 799,
    image: "/assets/ipadpro.jpg",
  },
  {
    id: 6,
    name: "Sony WH-1000XM5",
    description: "Noise-canceling wireless headphones",
    price: 399,
    image: "/assets/sonymxh00.jpg",
  },
  {
    id: 7,
    name: "Apple Watch Series 8",
    description: "Smartwatch with health and fitness tracking",
    price: 499,
    image: "/assets/apple series 8.jpg",
  },
  {
    id: 8,
    name: "Google Pixel 7",
    description: "Google's flagship smartphone with Android 13",
    price: 699,
    image: "/assets/pixel7.jpg",
  },
  {
    id: 9,
    name: "Amazon Echo Dot",
    description: "Smart speaker with Alexa",
    price: 49,
    image: "/assets/echodot.jpg",
  },
  {
    id: 10,
    name: "Fitbit Versa 4",
    description: "Fitness smartwatch with GPS",
    price: 179,
    image: "/assets/fitbitversa 4.jpg",
  },
  {
    id: 11,
    name: "Canon EOS R5",
    description: "Professional mirrorless camera",
    price: 3899,
    image: "/assets/CanonEOSR5.jpg",
  },
  {
    id: 12,
    name: "GoPro Hero 11",
    description: "Action camera for adventure recording",
    price: 499,
    image: "/assets/goprohero11.jpg",
  },
  {
    id: 13,
    name: "Nikon Z6 II",
    description: "Full-frame mirrorless camera",
    price: 1999,
    image: "/assets/nikonz6.jpg",
  },
  {
    id: 14,
    name: "Bose SoundLink",
    description: "Portable Bluetooth speaker",
    price: 129,
    image: "/assets/bosesoundlink.jpg",
  },
  {
    id: 15,
    name: "Samsung Galaxy Tab S8",
    description: "Android tablet with high refresh rate display",
    price: 749,
    image: "/assets/tab8.jpg",
  },
  {
    id: 16,
    name: "Logitech MX Master 3",
    description: "Advanced wireless mouse",
    price: 99,
    image: "/assets/logitechmsmaster.jpg",
  },
  {
    id: 17,
    name: "Razer BlackWidow V3",
    description: "Mechanical gaming keyboard",
    price: 129,
    image: "/assets/razorblackwidow.jpg",
  },
  {
    id: 18,
    name: "ASUS ROG Strix G15",
    description: "Gaming laptop with RTX 4070",
    price: 1599,
    image: "/assets/asusrog.jpg",
  },
  {
    id: 19,
    name: "Lenovo Legion 5",
    description: "Gaming laptop with Ryzen 7",
    price: 1299,
    image: "/assets/lenovolegion.jpg",
  },
  {
    id: 20,
    name: "OnePlus Buds Pro 2",
    description: "Wireless earbuds with ANC",
    price: 149,
    image: "/assets/oneplusbudspro2.jpg",
  },
];

export default products;
